NF: add fsck check for pseudo-key names in the asset file
psyinfra/onyo pull request #310
Opened 2023-03-14 10:44 UTC by TobiasKadelka

Adds the check to `Repo.fsck()`, and adds tests.

Close #283

2023-03-14 14:52 UTC, aqw requested changes

2023-03-14 14:52 UTC, aqw commented on onyo/lib/onyo.py
> +        - "no-pseudo-keys": verifies that assets do not contain pseudo-key names
IMO, the `no` should be dropped. It's a check for pseudo keys.

Have "no" in the name confuses the fact that "yes" we are doing the check.

2023-03-14 14:52 UTC, aqw commented on onyo/lib/onyo.py
> +                    if asset not in assets_with_pseudo_keys.keys():
No need for `.keys()` here. Simply: `if asset not in assets_with_pseudo_key:`

Nit: I find `assets_with_pseudo_keys.keys()` to be odd to read. Perhaps a more generic name, such as `assets_failed` or `assets_violation`?

2023-03-14 14:52 UTC, aqw commented on onyo/lib/onyo.py
> +        for asset in self.assets:
The rest of the for-loop can be simplified to:
```
violation_list = [x for x in pseudo_keys if x in self._read_asset(asset)]
if violation_list:
    assets_with_pseudo_keys[asset] = violation_list
```

2023-03-14 14:52 UTC, aqw commented on onyo/lib/onyo.py
> +            log.error('The following assets contain pseudo keys:\n' +
This should be even more explicit. The user may not know what a pseudo key is, or that it is not allowed. Currently this message just states a fact. At minimum it should add "which are reserved for use in the asset filename."

2023-03-14 14:52 UTC, aqw commented on onyo/lib/onyo.py
> +                                    ', '.join([str(k) for k in assets_with_pseudo_keys[asset]])
`k` is already a string; No need to re-cast.

`assets_with_pseudo_keys[asset]` is a list not a dict.

`[str(k) for k in assets_with_pseudo_keys[asset]]` can simply be `assets_with_pseudo_keys[asset]`.

2023-03-14 14:52 UTC, aqw commented on onyo/lib/onyo.py
> +                                    for asset in list(assets_with_pseudo_keys.keys())]))
`.keys()` is not necessary to loop over a dict. And if it were, `.keys()` would not need to be cast into a list in order to iterate over it.

Needless casting is a common error across these PRs. Please only do so when you know that it is necessary.

2023-03-14 14:52 UTC, aqw commented on tests/lib/test_Repo_fsck.py
> +contents = ["type: value",
Please also add a test where the "reserved" pseudo key is in the value, and thus should not fail. For example:

```
key: serial
```
and the more perverse:
```
key: "model: value"
```

2023-03-15 08:01 UTC, TobiasKadelka commented
I added the feedback (except the one I commented on) and pushed again, thanks.
I especially liked the other test-group of things that should still be allowed!

2023-03-15 13:16 UTC, aqw commented on onyo/lib/onyo.py
> +        for asset in self.assets:
Not that this looks to be a costly part of the code, but the list comprehension also reduces the number of assignments and appends dramatically.

2023-03-15 13:42 UTC, TobiasKadelka commented
Well, I added/updated it now anyways. Not sure if the difference is relevant, but until we have performance checks for large numbers of assets, there is also no harm in optimizing a little bit. Thanks!

2023-03-16 10:19 UTC, aqw approved these changes
LGTM!

2023-03-16 10:19 UTC, merged